apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://3.14.2.11:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNWNiNDhiNTBiM2VlYzlhYWYzNGUwMGQyYzAxM2Q4ZTM3Y2MwZDc0NyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGI2M2E3OThlMDg0ODNmOGQ3ZWYxYTc2MzFkYTJlYWEiLCJleHAiOjE1NjU3MTg5MTUsImlhdCI6MTU2NTY5MDExNSwic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.L7RnIyrKhY42iiVG-uGSMpnSJQRlcptiDWxUcZfKDtAEpN84Yfr6JVlZb9_oJheT5MSk3RUo_PwraZNazc-Y_R1lt7XVm3rh-turf4Ak0aVtPrd2AB0YgyI3SrSEZlYagZ_aIecAAXyvYg-U3d0Abs30r-PVWgP0_1Xa31-JrLLNH49vheKTwH80pMdIk7pA7-fpmxCSgxS65iO-0h0Mp-xm6QyhJ0VqBx7RMcybpVwScxFPW-IRSNTHYBNOCVPkDyfGH7zheLAJfcRPBmmUnkhJedIjj8yJDnek5U0lzmhdq_MBPiiy5322Ila_mRJraaRe0TlVO2ugYzPvId2QNw
