apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://3.14.2.11:8001
  name: mycluster
contexts:
- context:
    cluster: mycluster
    namespace: default
    user: admin
  name: mycluster-context
current-context: mycluster-context
kind: Config
preferences: {}
users:
- name: admin
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiMDIzYTQ1NWI2MmQ4Y2IwYjEyNGRjYTYxYmVkODEzZjNlNzBiZGUzYSIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoiYWRtaW4iLCJpc3MiOiJodHRwczovL215Y2x1c3Rlci5pY3A6OTQ0My9vaWRjL2VuZHBvaW50L09QIiwiYXVkIjoiMGI2M2E3OThlMDg0ODNmOGQ3ZWYxYTc2MzFkYTJlYWEiLCJleHAiOjE1NjUzNzUxNzMsImlhdCI6MTU2NTM0NjM3Mywic3ViIjoiYWRtaW4iLCJ0ZWFtUm9sZU1hcHBpbmdzIjpbXX0.lEGhZNgjx_ybNOdnxfpXBhMZTqrsBrHcdfhr05Iwq2kJtc6v02DgVf9yuIzdpLd9lMjH-xFMGVOBJX5QpjIff43KqZ6bd-SGidSugUql_vJdg0L05JIN-IWbZRX7lR88mAJ6GK59pDUbAhHwgsYzMS8pvjh_hhHUZbvcYoVuJt_JFAEROxsggxQmU7plJjUySonNOSFRcwOv0dA8-JZwiGyoCOb474404_0bv7UcSree24ouqMEFRa8aSDGY32KLBNHFl8Eh50jTIFVVPVElYxpvJp3K2i2Dj4Ke37YNf-nyN0m4yEItC27rVRj8f_8j9e5rBHYMikuloYyLHDoqbg
