apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  selector:
    matchLabels:
      app: $appname
  replicas: 1
  template:
    metadata:
      labels:
        app: $appname
    spec:
      containers:
      - name: $appname
        image: $targetrepo/$appname
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
